export const poseLevels = {
  BEGINNER: "beginner",
  INTERMEDIATE: "intermediate",
  ADVANCED: "advanced",
};

export const poses = [
  {
    id: "mountain",
    name: "Mountain Pose",
    sanskrit: "Tadasana",
    level: poseLevels.BEGINNER,
    category: "Standing",
    benefits: ["Improves posture", "Builds body awareness", "Grounds the breath"],
    cue: "Feet grounded, crown lifting, shoulders soft.",
  },
  {
    id: "upward-salute",
    name: "Upward Salute",
    sanskrit: "Urdhva Hastasana",
    level: poseLevels.BEGINNER,
    category: "Standing",
    benefits: ["Stretches the side body", "Opens the shoulders", "Energizes"],
    cue: "Inhale arms overhead, keep ribs drawing in.",
  },
  {
    id: "forward-fold",
    name: "Standing Forward Fold",
    sanskrit: "Uttanasana",
    level: poseLevels.BEGINNER,
    category: "Forward bend",
    benefits: ["Stretches hamstrings and calves", "Calms the mind", "Releases the neck"],
    cue: "Bend the knees as much as you need, let the head hang.",
  },
  {
    id: "half-lift",
    name: "Half Standing Forward Bend",
    sanskrit: "Ardha Uttanasana",
    level: poseLevels.BEGINNER,
    category: "Forward bend",
    benefits: ["Lengthens the spine", "Strengthens the back", "Stretches hamstrings"],
    cue: "Hands to shins, lengthen from tailbone to crown.",
  },
  {
    id: "plank",
    name: "Plank Pose",
    sanskrit: "Phalakasana",
    level: poseLevels.BEGINNER,
    category: "Arm balance",
    benefits: ["Strengthens the core", "Builds arm and wrist strength", "Tones the whole body"],
    cue: "Shoulders over wrists, one long line from head to heels.",
  },
  {
    id: "chaturanga",
    name: "Four-Limbed Staff Pose",
    sanskrit: "Chaturanga Dandasana",
    level: poseLevels.INTERMEDIATE,
    category: "Arm balance",
    benefits: ["Strengthens arms and wrists", "Tones the core", "Prepares for arm balances"],
    cue: "Elbows hug in, lower halfway with a straight body.",
  },
  {
    id: "cobra",
    name: "Cobra Pose",
    sanskrit: "Bhujangasana",
    level: poseLevels.BEGINNER,
    category: "Backbend",
    benefits: ["Strengthens the spine", "Opens the chest", "Relieves stiffness in the lower back"],
    cue: "Press the tops of the feet down, lift with the back, not the hands.",
  },
  {
    id: "upward-dog",
    name: "Upward-Facing Dog",
    sanskrit: "Urdhva Mukha Svanasana",
    level: poseLevels.INTERMEDIATE,
    category: "Backbend",
    benefits: ["Opens chest and shoulders", "Strengthens arms and spine", "Improves posture"],
    cue: "Thighs lift off the mat, shoulders roll back and down.",
  },
  {
    id: "downward-dog",
    name: "Downward-Facing Dog",
    sanskrit: "Adho Mukha Svanasana",
    level: poseLevels.BEGINNER,
    category: "Inversion",
    benefits: ["Stretches hamstrings and calves", "Strengthens arms and shoulders", "Energizes the body"],
    cue: "Hips high, press the floor away, heels reach down.",
  },
  {
    id: "warrior-1",
    name: "Warrior I",
    sanskrit: "Virabhadrasana I",
    level: poseLevels.BEGINNER,
    category: "Standing",
    benefits: ["Strengthens legs", "Opens hips and chest", "Builds focus"],
    cue: "Front knee over ankle, hips square forward, arms reach up.",
  },
  {
    id: "warrior-2",
    name: "Warrior II",
    sanskrit: "Virabhadrasana II",
    level: poseLevels.BEGINNER,
    category: "Standing",
    benefits: ["Strengthens legs and ankles", "Opens the hips", "Builds stamina"],
    cue: "Arms wide, gaze over the front fingers, front knee tracks the toes.",
  },
  {
    id: "triangle",
    name: "Triangle Pose",
    sanskrit: "Trikonasana",
    level: poseLevels.BEGINNER,
    category: "Standing",
    benefits: ["Stretches hamstrings and side body", "Opens the chest", "Improves balance"],
    cue: "Reach forward, then tilt; both sides of the waist stay long.",
  },
  {
    id: "tree",
    name: "Tree Pose",
    sanskrit: "Vrksasana",
    level: poseLevels.BEGINNER,
    category: "Balance",
    benefits: ["Improves balance", "Strengthens ankles and legs", "Builds concentration"],
    cue: "Foot to calf or thigh, never the knee. Fix your gaze on one point.",
  },
  {
    id: "chair",
    name: "Chair Pose",
    sanskrit: "Utkatasana",
    level: poseLevels.BEGINNER,
    category: "Standing",
    benefits: ["Strengthens thighs and glutes", "Builds heat", "Tones the core"],
    cue: "Sit back as if into a chair, weight in the heels.",
  },
  {
    id: "crow",
    name: "Crow Pose",
    sanskrit: "Bakasana",
    level: poseLevels.ADVANCED,
    category: "Arm balance",
    benefits: ["Strengthens arms and wrists", "Tones the core", "Builds confidence"],
    cue: "Knees high on the upper arms, gaze forward, shift weight slowly.",
  },
  {
    id: "wheel",
    name: "Wheel Pose",
    sanskrit: "Urdhva Dhanurasana",
    level: poseLevels.ADVANCED,
    category: "Backbend",
    benefits: ["Opens chest and shoulders", "Strengthens arms, legs and spine", "Energizes"],
    cue: "Hands by the ears, press evenly through hands and feet.",
  },
  {
    id: "headstand",
    name: "Supported Headstand",
    sanskrit: "Salamba Sirsasana",
    level: poseLevels.ADVANCED,
    category: "Inversion",
    benefits: ["Strengthens shoulders and core", "Improves focus", "Builds balance"],
    cue: "Forearms carry the weight, not the head. Practise near a wall.",
  },
  {
    id: "pigeon",
    name: "Pigeon Pose",
    sanskrit: "Eka Pada Rajakapotasana",
    level: poseLevels.INTERMEDIATE,
    category: "Hip opener",
    benefits: ["Opens the hips", "Stretches the glutes and hip flexors", "Releases tension"],
    cue: "Front shin angled, back leg long, square the hips.",
  },
  {
    id: "bridge",
    name: "Bridge Pose",
    sanskrit: "Setu Bandha Sarvangasana",
    level: poseLevels.BEGINNER,
    category: "Backbend",
    benefits: ["Strengthens glutes and back", "Opens the chest", "Calms the mind"],
    cue: "Feet hip-width, press down to lift the hips.",
  },
  {
    id: "seated-forward-bend",
    name: "Seated Forward Bend",
    sanskrit: "Paschimottanasana",
    level: poseLevels.BEGINNER,
    category: "Forward bend",
    benefits: ["Stretches the back of the body", "Calms the nervous system", "Aids digestion"],
    cue: "Lead with the chest, not the head. Bend the knees if needed.",
  },
  {
    id: "supine-twist",
    name: "Supine Spinal Twist",
    sanskrit: "Supta Matsyendrasana",
    level: poseLevels.BEGINNER,
    category: "Twist",
    benefits: ["Releases the lower back", "Mobilizes the spine", "Relaxes the body"],
    cue: "Knees drop to one side, both shoulders stay heavy.",
  },
  {
    id: "childs-pose",
    name: "Child's Pose",
    sanskrit: "Balasana",
    level: poseLevels.BEGINNER,
    category: "Restorative",
    benefits: ["Gently stretches hips and back", "Calms the mind", "A place to rest anytime"],
    cue: "Knees wide or together, forehead rests, breathe into the back.",
  },
  {
    id: "cat-cow",
    name: "Cat-Cow",
    sanskrit: "Marjaryasana-Bitilasana",
    level: poseLevels.BEGINNER,
    category: "Warm-up",
    benefits: ["Mobilizes the spine", "Warms up the back", "Links breath and movement"],
    cue: "Inhale drop the belly, exhale round the back.",
  },
  {
    id: "corpse",
    name: "Corpse Pose",
    sanskrit: "Savasana",
    level: poseLevels.BEGINNER,
    category: "Restorative",
    benefits: ["Deep relaxation", "Lets the practice settle", "Reduces stress"],
    cue: "Let everything go. Breathe naturally.",
  },
];

export const getPose = (id) => poses.find((pose) => pose.id === id);

// Each step holds a pose for `seconds`. `side` is shown for one-sided poses.
export const flows = [
  {
    id: "morning-wake-up",
    name: "Morning Wake-Up",
    level: poseLevels.BEGINNER,
    description: "A gentle 5-minute flow to wake up the spine and legs.",
    steps: [
      { poseId: "childs-pose", seconds: 30 },
      { poseId: "cat-cow", seconds: 30 },
      { poseId: "downward-dog", seconds: 30 },
      { poseId: "forward-fold", seconds: 20 },
      { poseId: "mountain", seconds: 15 },
      { poseId: "upward-salute", seconds: 15 },
      { poseId: "chair", seconds: 20 },
      { poseId: "tree", seconds: 30, side: "right" },
      { poseId: "tree", seconds: 30, side: "left" },
      { poseId: "supine-twist", seconds: 30, side: "right" },
      { poseId: "supine-twist", seconds: 30, side: "left" },
      { poseId: "corpse", seconds: 60 },
    ],
  },
  {
    id: "sun-salutation-a",
    name: "Sun Salutation A",
    level: poseLevels.INTERMEDIATE,
    description: "The classic Surya Namaskar A, one round with a short rest.",
    steps: [
      { poseId: "mountain", seconds: 10 },
      { poseId: "upward-salute", seconds: 8 },
      { poseId: "forward-fold", seconds: 8 },
      { poseId: "half-lift", seconds: 6 },
      { poseId: "plank", seconds: 10 },
      { poseId: "chaturanga", seconds: 6 },
      { poseId: "upward-dog", seconds: 8 },
      { poseId: "downward-dog", seconds: 25 },
      { poseId: "half-lift", seconds: 6 },
      { poseId: "forward-fold", seconds: 8 },
      { poseId: "upward-salute", seconds: 8 },
      { poseId: "mountain", seconds: 10 },
      { poseId: "childs-pose", seconds: 30 },
    ],
  },
  {
    id: "standing-strength",
    name: "Standing Strength",
    level: poseLevels.INTERMEDIATE,
    description: "Warriors and triangle on both sides to build leg strength.",
    steps: [
      { poseId: "mountain", seconds: 20 },
      { poseId: "downward-dog", seconds: 30 },
      { poseId: "warrior-1", seconds: 30, side: "right" },
      { poseId: "warrior-2", seconds: 30, side: "right" },
      { poseId: "triangle", seconds: 30, side: "right" },
      { poseId: "downward-dog", seconds: 20 },
      { poseId: "warrior-1", seconds: 30, side: "left" },
      { poseId: "warrior-2", seconds: 30, side: "left" },
      { poseId: "triangle", seconds: 30, side: "left" },
      { poseId: "childs-pose", seconds: 30 },
      { poseId: "corpse", seconds: 60 },
    ],
  },
  {
    id: "evening-wind-down",
    name: "Evening Wind-Down",
    level: poseLevels.BEGINNER,
    description: "Slow, floor-based poses to relax before sleep.",
    steps: [
      { poseId: "childs-pose", seconds: 45 },
      { poseId: "cat-cow", seconds: 30 },
      { poseId: "pigeon", seconds: 45, side: "right" },
      { poseId: "pigeon", seconds: 45, side: "left" },
      { poseId: "seated-forward-bend", seconds: 45 },
      { poseId: "bridge", seconds: 30 },
      { poseId: "supine-twist", seconds: 30, side: "right" },
      { poseId: "supine-twist", seconds: 30, side: "left" },
      { poseId: "corpse", seconds: 90 },
    ],
  },
];

export const getFlow = (id) => flows.find((flow) => flow.id === id);

export const flowDuration = (flow) =>
  flow.steps.reduce((total, step) => total + step.seconds, 0);

export const formatTime = (totalSeconds) => {
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${String(seconds).padStart(2, "0")}`;
};
